services:
  - type: web
    name: sortify-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: "3.12"
      - key: DATABASE_URL
        scope: shared
